name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'


permissions:
  contents: read

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@1919f6c305aea6ab10e6181a8ddf72317ad77e0e # v2

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
